FROM node:18 AS builder
WORKDIR /home/node/app
COPY project /home/node/app
RUN npm install



FROM node:alpine
WORKDIR /home/node/app
COPY --from=builder /home/node/app /home/node/app
EXPOSE 7010
CMD ["npm", "run", "dev"]
